// Demo seed: fills the database with papers covering every review state, and
// writes a real openable PDF for each one.
//
// Run with:  npm run db:seed
//
// Why this exists: an empty site demos badly, and the previous hand-made test
// rows pointed at 69-byte stub files that no PDF viewer will open — clicking
// "Download" during a demo produced a broken file. This regenerates both halves
// together so the row and the file on disk always agree.
//
// DESTRUCTIVE: drops every Paper, Notification and EmailLog row before
// inserting. User accounts are preserved (upserted by email) so an open dev
// session survives a reseed.
//
// Talks to SQLite directly through better-sqlite3 rather than the Prisma client:
// the Prisma 7 client is generated as TypeScript, which a plain .mjs script
// cannot import without a build step. Seeding is a handful of INSERTs, so the
// type safety is not worth the toolchain.

import Database from "better-sqlite3";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

process.loadEnvFile?.();

// Mirrors src/lib/storage.ts — keep the default in sync with it.
const UPLOAD_DIR = process.env.UPLOAD_DIR ?? "var/uploads";

// DATABASE_URL is a Prisma connection string ("file:./prisma/dev.db"), not a
// path. Strip the scheme so better-sqlite3 can open it.
const DB_PATH = (process.env.DATABASE_URL ?? "file:./prisma/dev.db").replace(
  /^file:/,
  "",
);

// ---------------------------------------------------------------------------
// Minimal PDF writer
// ---------------------------------------------------------------------------
// Hand-rolled rather than pulled from npm so `npm run db:seed` works on a fresh
// clone with no extra install. Produces a genuinely valid multi-page PDF —
// Preview, Chrome and Acrobat all open it — using the two base-14 fonts, which
// every reader has built in so nothing needs embedding.

const PAGE_W = 595; // A4 at 72dpi
const PAGE_H = 842;
const MARGIN = 70;
const BODY_W = PAGE_W - MARGIN * 2;

/** Escape the three characters that are syntax inside a PDF string literal. */
function pdfEscape(text) {
  return text.replace(/[\\()]/g, (c) => `\\${c}`);
}

/**
 * Drop anything outside Latin-1. The base-14 fonts are single-byte encoded, so
 * a stray em-dash or curly quote would render as garbage rather than fail
 * loudly. Demo copy is ASCII anyway; this is a guard, not a transliterator.
 */
function toLatin1(text) {
  return text.replace(/[^\x20-\x7E]/g, "-");
}

/**
 * Greedy word wrap. Helvetica glyph widths average ~0.5em, so characters-per-
 * line is a good enough proxy for real metrics at these sizes — the only cost
 * of being slightly off is a ragged right edge on a sample document.
 */
function wrap(text, fontSize, width = BODY_W) {
  const maxChars = Math.floor(width / (fontSize * 0.5));
  const lines = [];
  let line = "";
  for (const word of toLatin1(text).split(/\s+/)) {
    if (!line) line = word;
    else if (line.length + 1 + word.length <= maxChars) line += ` ${word}`;
    else {
      lines.push(line);
      line = word;
    }
  }
  if (line) lines.push(line);
  return lines;
}

/**
 * Lay a list of {text, size, font, gap} blocks onto pages, breaking whenever the
 * cursor runs past the bottom margin. Returns an array of content streams.
 */
function paginate(blocks) {
  const pages = [];
  let ops = [];
  let y = PAGE_H - MARGIN;

  for (const block of blocks) {
    for (const line of wrap(block.text, block.size)) {
      if (y < MARGIN + block.size) {
        pages.push(ops);
        ops = [];
        y = PAGE_H - MARGIN;
      }
      ops.push(
        `BT /${block.font} ${block.size} Tf ${MARGIN} ${y.toFixed(1)} Td (${pdfEscape(line)}) Tj ET`,
      );
      y -= block.size * 1.45;
    }
    y -= block.gap ?? 0;
  }
  pages.push(ops);
  return pages.map((page) => page.join("\n"));
}

function buildPdf({ title, authorLine, abstract, status, slug }) {
  const streams = paginate([
    { text: "CENTRAL ASIAN REVIEW", size: 9, font: "F2", gap: 18 },
    { text: title, size: 19, font: "F2", gap: 6 },
    { text: authorLine, size: 11, font: "F1", gap: 4 },
    { text: `Status: ${status}  -  /p/${slug}`, size: 9, font: "F1", gap: 22 },
    { text: "ABSTRACT", size: 10, font: "F2", gap: 6 },
    { text: abstract, size: 11, font: "F1", gap: 22 },
    { text: "1.  INTRODUCTION", size: 10, font: "F2", gap: 6 },
    {
      text:
        "This is sample content generated by scripts/seed-demo.mjs so the demo " +
        "site has a real, openable document behind every download link. It is " +
        "not a research paper. The abstract above is the text search engines " +
        "index; everything past this point sits behind the sign-in gate, which " +
        "is the behaviour this file exists to demonstrate.",
      size: 11,
      font: "F1",
      gap: 16,
    },
    { text: "2.  METHOD", size: 10, font: "F2", gap: 6 },
    {
      text:
        "Placeholder section. Page two below exists so the pager in a PDF " +
        "viewer has something to page through during the walkthrough.",
      size: 11,
      font: "F1",
      gap: 400,
    },
    { text: "3.  RESULTS", size: 10, font: "F2", gap: 6 },
    {
      text:
        "Placeholder section on a second page. Replace this whole file with a " +
        "genuine upload through /submit to see the real submission path.",
      size: 11,
      font: "F1",
    },
  ]);

  // Object numbering: 1 catalog, 2 pages, 3 + 4 fonts, then a page object and a
  // content stream per page, interleaved.
  const objects = [];
  const pageIds = streams.map((_, i) => 5 + i * 2);

  objects[1] = "<< /Type /Catalog /Pages 2 0 R >>";
  objects[2] =
    `<< /Type /Pages /Count ${streams.length} ` +
    `/Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] >>`;
  objects[3] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";
  objects[4] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>";

  streams.forEach((stream, i) => {
    const pageId = pageIds[i];
    objects[pageId] =
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] ` +
      `/Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${pageId + 1} 0 R >>`;
    objects[pageId + 1] =
      `<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`;
  });

  // Serialise, recording the byte offset of each object for the xref table. A
  // wrong offset here is what makes a hand-built PDF fail to open.
  let out = "%PDF-1.4\n";
  const offsets = [];
  for (let i = 1; i < objects.length; i++) {
    offsets[i] = Buffer.byteLength(out);
    out += `${i} 0 obj\n${objects[i]}\nendobj\n`;
  }

  const xrefStart = Buffer.byteLength(out);
  out += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
  for (let i = 1; i < objects.length; i++) {
    out += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  out +=
    `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\n` +
    `startxref\n${xrefStart}\n%%EOF\n`;

  return Buffer.from(out, "latin1");
}

// ---------------------------------------------------------------------------
// Demo content
// ---------------------------------------------------------------------------

const iso = (s) => new Date(`${s}T09:00:00Z`).toISOString();

// storedName must match STORED_NAME_PATTERN in src/lib/storage.ts (a 36-char
// uuid + .pdf). Fixed rather than random so reseeding overwrites the same files
// instead of littering the upload directory.
const uuid = (n) => `000000${String(n).padStart(2, "0")}-0000-4000-8000-000000000000`;

const ACCOUNTS = [
  { key: "admin", email: "dev-admin@freshman.academy", name: "Dev Editor", role: "ADMIN" },
  { key: "reader", email: "dev-reader@freshman.academy", name: "Dev Reader", role: "READER" },
  { key: "karimova", email: "a.karimova@example.edu", name: "A. Karimova", role: "READER" },
  { key: "iskakov", email: "m.iskakov@example.edu", name: "M. Iskakov", role: "READER" },
];

const PAPERS = [
  {
    slug: "border-trade-ferghana",
    title: "Border Trade in the Ferghana Valley",
    authorLine: "S. Ito, K. Mamatov",
    abstract:
      "Reopened crossings have revived small-scale trade across the valley, but the gains are concentrated among traders who already held permits. This paper draws on market surveys at four crossings to show how informal brokerage persists alongside the formal regime.",
    status: "PUBLISHED",
    submitter: "karimova",
    submitted: "2026-06-02",
    published: "2026-06-14",
  },
  {
    slug: "water-allocation-syr-darya",
    title: "Water Allocation on the Syr Darya After 2020",
    authorLine: "D. Abdullaev, M. Sultanova",
    abstract:
      "Upstream storage decisions and downstream irrigation demand have diverged sharply since 2020. This paper reconstructs seasonal release schedules from gauge data and interviews with basin authorities, and argues that the current allocation framework understates winter energy pressure.",
    status: "PUBLISHED",
    submitter: "karimova",
    submitted: "2026-06-11",
    published: "2026-06-25",
  },
  {
    slug: "rail-freight-corridors",
    title: "Rail Freight Corridors and the Middle Route",
    authorLine: "B. Toktogulov",
    abstract:
      "Container volumes across the Trans-Caspian route tripled between 2022 and 2025. Drawing on customs records and operator schedules, this paper examines whether the growth reflects durable capacity or temporary rerouting, and what the difference implies for port investment.",
    status: "PUBLISHED",
    submitter: "iskakov",
    submitted: "2026-06-20",
    published: "2026-07-01",
  },
  {
    slug: "labour-migration-remittances",
    title: "Labour Migration and Remittance Dependence",
    authorLine: "N. Ergasheva, T. Rakhimov",
    abstract:
      "Remittances account for a substantial share of household income across the region, but the composition of sending countries has shifted. This paper uses panel survey data to trace how destination choice responds to currency shocks and visa policy.",
    status: "PUBLISHED",
    submitter: "reader",
    submitted: "2026-06-28",
    published: "2026-07-09",
  },
  {
    slug: "urban-heat-tashkent",
    title: "Urban Heat and Building Stock in Tashkent",
    authorLine: "S. Yusupova",
    abstract:
      "Summer peak temperatures in the city centre now regularly exceed surrounding districts by several degrees. Combining satellite thermal imagery with a survey of Soviet-era housing stock, this paper identifies which retrofit measures would deliver the largest reduction.",
    status: "PUBLISHED",
    submitter: "karimova",
    submitted: "2026-07-03",
    published: "2026-07-16",
  },
  {
    slug: "higher-education-reform",
    title: "Higher Education Reform and Graduate Outcomes",
    authorLine: "A. Karimova, J. Nazarov",
    abstract:
      "A decade of university expansion has produced more graduates without a matching rise in skilled employment. This paper links enrolment records to tax data to measure returns by field of study, and finds the gap concentrated in a small number of programmes.",
    status: "PUBLISHED",
    submitter: "karimova",
    submitted: "2026-07-10",
    published: "2026-07-24",
  },
  {
    slug: "gas-pricing-reform",
    title: "Gas Pricing Reform and Household Burden",
    authorLine: "M. Iskakov, L. Orozova",
    abstract:
      "Tariff liberalisation has shifted a growing share of heating costs onto households, unevenly across income deciles. This paper models the distributional effect of the 2025 schedule and tests two compensation designs against it.",
    status: "SUBMITTED",
    submitter: "iskakov",
    submitted: "2026-07-27",
  },
  {
    slug: "pastoral-land-tenure",
    title: "Pastoral Land Tenure and Winter Pasture Access",
    authorLine: "G. Beksultanova",
    abstract:
      "Formal pasture leases have expanded rapidly, but herders report shrinking practical access to winter grazing. This paper contrasts the lease register with GPS herd tracks over three seasons to locate where paper rights and physical use diverge.",
    status: "SUBMITTED",
    submitter: "reader",
    submitted: "2026-07-30",
  },
  {
    slug: "digital-payments-adoption",
    title: "Digital Payments Adoption Among Bazaar Traders",
    authorLine: "R. Nurlanov",
    abstract:
      "Card and QR acceptance has grown fastest among traders who already kept written books. This paper surveys two hundred stalls to separate the effect of tax formalisation from that of customer demand.",
    status: "REJECTED",
    // Deliberately the reader account: the localhost dev login only offers
    // "editor" and "reader", so a returned paper parked on any other author is
    // unreachable in a demo and the reviewNote never gets seen.
    submitter: "reader",
    submitted: "2026-07-18",
    reviewNote:
      "Promising data, but the abstract reads as a teaser rather than a summary — it does not state the finding. Since the abstract is the only text search engines can see, please rewrite it to stand alone and resubmit. Also add the survey instrument as an appendix.",
  },
  {
    slug: "regional-airline-liberalisation",
    title: "Regional Airline Liberalisation and Route Density",
    authorLine: "T. Sagyndyk",
    abstract:
      "Open-skies agreements signed since 2023 have added carriers without adding city pairs. This draft assembles a schedule panel to test whether liberalisation has widened the network or only thickened existing trunk routes.",
    status: "DRAFT",
    submitter: "reader",
  },
];

// ---------------------------------------------------------------------------
// Seed
// ---------------------------------------------------------------------------

const db = new Database(DB_PATH);
db.pragma("foreign_keys = ON");

// Refuse to destroy work that did not come from this script.
//
// Everything seeded here carries a "demo-" id prefix, so anything without one is
// a real submission that arrived through /submit — on the deployed site that is
// somebody's actual paper, and the PDF is not recoverable from anywhere else.
// Overridable because wiping a staging box on purpose is legitimate.
const realPapers = db
  .prepare("SELECT COUNT(*) AS n FROM Paper WHERE id NOT LIKE 'demo-%'")
  .get().n;

if (realPapers > 0 && process.env.SEED_FORCE !== "1") {
  console.error(
    `Refusing to seed: ${realPapers} paper(s) in ${DB_PATH} were not created by ` +
      `this script, and seeding deletes every paper row.\n` +
      `Their uploaded PDFs would be orphaned on disk with no way to match them ` +
      `back up.\n\n` +
      `If you really mean to wipe them, re-run with SEED_FORCE=1.`,
  );
  db.close();
  process.exit(1);
}

mkdirSync(UPLOAD_DIR, { recursive: true });

const userIds = {};

db.transaction(() => {
  // Papers cascade-delete their notifications only via User, so clear the
  // dependent tables explicitly.
  db.prepare("DELETE FROM Notification").run();
  db.prepare("DELETE FROM EmailLog").run();
  db.prepare("DELETE FROM Paper").run();

  const findUser = db.prepare("SELECT id FROM User WHERE email = ?");
  const insertUser = db.prepare(
    `INSERT INTO User (id, name, email, role, createdAt)
     VALUES (@id, @name, @email, @role, @createdAt)`,
  );
  const updateUser = db.prepare(
    "UPDATE User SET name = @name, role = @role WHERE id = @id",
  );

  for (const account of ACCOUNTS) {
    const existing = findUser.get(account.email);
    if (existing) {
      // Keep the id so any live session still resolves to this user.
      userIds[account.key] = existing.id;
      updateUser.run({ id: existing.id, name: account.name, role: account.role });
    } else {
      const id = `demo-user-${account.key}`;
      userIds[account.key] = id;
      insertUser.run({ ...account, id, createdAt: iso("2026-05-20") });
    }
  }

  const insertPaper = db.prepare(
    `INSERT INTO Paper (id, slug, title, abstract, authorLine, status, reviewNote,
                        storedName, originalName, fileSize, submitterId, reviewerId,
                        createdAt, updatedAt, submittedAt, publishedAt)
     VALUES (@id, @slug, @title, @abstract, @authorLine, @status, @reviewNote,
             @storedName, @originalName, @fileSize, @submitterId, @reviewerId,
             @createdAt, @updatedAt, @submittedAt, @publishedAt)`,
  );

  PAPERS.forEach((paper, i) => {
    const storedName = `${uuid(i + 1)}.pdf`;
    const bytes = buildPdf(paper);
    writeFileSync(path.join(UPLOAD_DIR, storedName), bytes);

    // A reviewer is recorded only once a decision has actually been made.
    const reviewed = paper.status === "PUBLISHED" || paper.status === "REJECTED";
    const created = paper.submitted ?? "2026-07-31";

    insertPaper.run({
      id: `demo-paper-${paper.slug}`,
      slug: paper.slug,
      title: paper.title,
      abstract: paper.abstract,
      authorLine: paper.authorLine,
      status: paper.status,
      reviewNote: paper.reviewNote ?? null,
      storedName,
      originalName: `${paper.slug}.pdf`,
      // The real byte count, so the size shown in the UI matches the download.
      fileSize: bytes.byteLength,
      submitterId: userIds[paper.submitter],
      reviewerId: reviewed ? userIds.admin : null,
      createdAt: iso(created),
      updatedAt: iso(paper.published ?? created),
      submittedAt: paper.submitted ? iso(paper.submitted) : null,
      publishedAt: paper.published ? iso(paper.published) : null,
    });
  });

  // Notifications: one unread pair for the editor (so the bell shows a count)
  // and a decision each way for the authors.
  const insertNotification = db.prepare(
    `INSERT INTO Notification (id, userId, kind, title, body, href, readAt, createdAt)
     VALUES (@id, @userId, @kind, @title, @body, @href, @readAt, @createdAt)`,
  );

  const notifications = [
    {
      id: "demo-notif-1",
      userId: userIds.admin,
      kind: "SUBMISSION_RECEIVED",
      title: "New submission: Pastoral Land Tenure and Winter Pasture Access",
      body: "Submitted by Dev Reader and waiting for review.",
      href: "/admin",
      readAt: null,
      createdAt: iso("2026-07-30"),
    },
    {
      id: "demo-notif-2",
      userId: userIds.admin,
      kind: "SUBMISSION_RECEIVED",
      title: "New submission: Gas Pricing Reform and Household Burden",
      body: "Submitted by M. Iskakov and waiting for review.",
      href: "/admin",
      readAt: null,
      createdAt: iso("2026-07-27"),
    },
    {
      id: "demo-notif-3",
      userId: userIds.reader,
      kind: "PAPER_RETURNED",
      title: "Returned for revision: Digital Payments Adoption Among Bazaar Traders",
      body: "The editor left a note explaining what to change.",
      href: "/submissions",
      readAt: null,
      createdAt: iso("2026-07-22"),
    },
    {
      id: "demo-notif-4",
      userId: userIds.karimova,
      kind: "PAPER_PUBLISHED",
      title: "Published: Higher Education Reform and Graduate Outcomes",
      body: "Your paper is now live on the public index.",
      href: "/p/higher-education-reform",
      readAt: iso("2026-07-25"),
      createdAt: iso("2026-07-24"),
    },
  ];
  for (const notification of notifications) insertNotification.run(notification);

  // Email log. SKIPPED is what local dev actually produces (no RESEND_API_KEY);
  // SENT and FAILED are included so the admin email page shows all three states.
  const insertEmail = db.prepare(
    `INSERT INTO EmailLog (id, recipient, subject, status, error, paperId, createdAt)
     VALUES (@id, @recipient, @subject, @status, @error, @paperId, @createdAt)`,
  );

  const emails = [
    {
      id: "demo-email-1",
      recipient: "a.karimova@example.edu",
      subject: "Your paper has been published",
      status: "SENT",
      error: null,
      paperId: "demo-paper-higher-education-reform",
      createdAt: iso("2026-07-24"),
    },
    {
      id: "demo-email-2",
      recipient: "m.iskakov@example.edu",
      subject: "Your submission needs revision",
      status: "SKIPPED",
      error: null,
      paperId: "demo-paper-digital-payments-adoption",
      createdAt: iso("2026-07-22"),
    },
    {
      id: "demo-email-3",
      recipient: "bounce@example.edu",
      subject: "Your paper has been published",
      status: "FAILED",
      error: "Recipient address rejected by provider (550)",
      paperId: "demo-paper-urban-heat-tashkent",
      createdAt: iso("2026-07-16"),
    },
  ];
  for (const email of emails) insertEmail.run(email);
})();

const counts = db
  .prepare(
    `SELECT status, COUNT(*) AS n FROM Paper GROUP BY status ORDER BY status`,
  )
  .all();

db.close();

console.log(`Seeded ${DB_PATH}`);
for (const { status, n } of counts) console.log(`  ${status.padEnd(10)} ${n}`);
console.log(`PDFs written to ${UPLOAD_DIR}/`);
console.log("\nSign in at /login with the localhost dev buttons:");
console.log("  Continue as editor  -> review queue at /admin");
console.log("  Continue as reader  -> own submissions at /submissions");
